export const theme = {
  color: {
    primary: "#31E5AF",
    background: "#181818",
    darkgray: "#2F2F2F",
    gray: "#232429",
    gray900: "#393A3F",
    gray800: "#55565B",
    gray700: "#75767B",
    gray600: "#828388",
    gray500: "#919297",
    gray400: "#ADAEB3",
    gray300: "#C1C2C7",
    gray200: "#D3D4D9",
    gray100: "#DEDFE4",
    gray050: "#F3F4F9",
    lightgray: "#ACACAC",
    kakao: "#FFE500",
    white: "#FFFFFF",
    black: "#000000",
    transparent: "transparent",
  },
  fontstyle: {
    display: "font-size: 1.8rem; font-family: \"JalnanGothic\";",
    subhead3: "font-size: 1.6rem; font-family: \"JalnanGothic\";",
    subhead2: "font-size: 1.4rem; font-family: \"JalnanGothic\";",
    subhead1: "font-size: 1.2rem; font-family: \"JalnanGothic\";",
    body3Medium: "font-size: 1.8rem; font-weight: 500; font-family: \"Pretendard\";",
    body3Regular: "font-size: 1.8rem; font-weight: 400; font-family: \"Pretendard\";",
    body2Medium: "font-size: 1.6rem; font-weight: 500; font-family: \"Pretendard\";",
    body2Regular: "font-size: 1.6rem; font-weight: 400; font-family: \"Pretendard\";",
    body1Medium: "font-size: 1.4rem; font-weight: 500; font-family: \"Pretendard\";",
    body1Regular: "font-size: 1.4rem; font-weight: 400; font-family: \"Pretendard\";",
    captionMedium: "font-size: 1.2rem; font-weight: 500; font-family: \"Pretendard\";",
    captionRegular: "font-size: 1.2rem; font-weight: 400; font-family: \"Pretendard\";",
    descriptionMedium: "font-size: 1rem; font-weight: 500; font-family: \"Pretendard\";",
    descriptionRegular: "font-size: 1rem; font-weight: 400; font-family: \"Pretendard\";",
  },
  page: {
    maxWidth: "1000px",
  },
  space: {
    spacePage: "5.2rem",
    space3Xl: "3rem",
    space2Xl: "2.5rem",
    spaceXl: "2rem",
    spaceLg: "1.5rem",
    spaceMd: "1rem",
    spaceSm: "0.5rem",
    spaceXs: "0.2rem",
    spaceZero: "0rem",
  },
  radius: {
    radius3Xl: "2rem",
    radius2Xl: "1.6rem",
    radiusXl: "1.2rem",
    radiusLg: "0.8rem",
    radiusMd: "0.6rem",
    radiusSm: "0.4rem",
    radiusxs: "0.2rem",
  },
  icon: {
    icon2Xl: "4.8rem",
    iconXl: "3.6rem",
    iconLg: "2.4rem",
    iconMd: "1.6rem",
    iconSm: "1.2rem",
  },
  device: {
    wide: "only screen and (min-width: 1920px)",
    lg: "only screen and (min-width: 1008px)",
    sm_md: "only screen and (max-width: 1007px)",
    md: "only screen and (min-width: 641px) and (max-width: 1007px)",
    sm: "only screen and (max-width: 640px)",
    not_sm: "only screen and (min-width: 641px)",
    md_lg: "only screen and (min-width: 641px)",
  },
};
